version: '3'
services:          
    school_web:
        build: .     
        container_name: school_web
        env_file:
            - .env
        ports:
            - "6002:80"
        volumes: 
            - ./:/frontend
            - /frontend/node_modules
        networks:
        - local
        - webgateway
        labels:
        - traefik.http.routers.school_web.rule=Host(`school.slightlytechie.com`)
        - traefik.http.routers.school_web.tls=true
        - traefik.http.routers.school_web.tls.certresolver=lets-encrypt
        - traefik.port=6002        
networks:
  local:
  webgateway:
    external: true