version: '3'
services:          
    frontend:
        build: .     
        container_name: frontend
        ports:
            - "3000:80"
        volumes: 
            - ./:/frontend
            - /frontend/node_modules